name: gearhaven
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  http: ^1.1.2
  otp_text_field: ^1.1.3
  dio: ^5.4.1
  image_picker: ^1.0.7
  khalti_flutter: ^3.0.0
  timeline_tile: ^2.0.0
  get_ip_address: ^0.0.6
  dart_ipify: ^1.1.1
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^17.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/imgs/
    - assets/svgs/

